/* CREATING DATABASE  */

CREATE DATABASE MONDAY_COFFEE

/* CREATING CITY TABLE */

DROP TABLE IF EXISTS CITY
CREATE TABLE CITY
(
	CITY_ID	INT PRIMARY KEY,
	CITY_NAME VARCHAR(15),	
	POPULATION	BIGINT,
	ESTIMATED_RENT	FLOAT,
	CITY_RANK INT
)

/* CREATING CUSTOMERS TABLE */

DROP TABLE IF EXISTS CUSTOMERS
CREATE TABLE CUSTOMERS
(
	CUSTOMER_ID INT PRIMARY KEY,	
	CUSTOMER_NAME VARCHAR(25),	
	CITY_ID INT,
	FOREIGN KEY (CITY_ID) REFERENCES CITY(CITY_ID)
)

/* CREATING PRODUCTS TABLE */

DROP TABLE IF EXISTS PRODUCTS
CREATE TABLE PRODUCTS
(
	PRODUCT_ID	INT PRIMARY KEY,
	PRODUCT_NAME VARCHAR(35),	
	PRICE FLOAT
)

/* CREATING SALES TABLE */

DROP TABLE IF EXISTS SALES
CREATE TABLE SALES
(
	SALE_ID	INT PRIMARY KEY,
	SALE_DATE DATE,
	PRODUCT_ID	INT,
	CUSTOMER_ID	INT,
	TOTAL FLOAT,
	RATING INT,
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID) 
)

--IMPORT DATASETS RULES
--1ST IMPORT TO CITY
--2ND IMPORT TO PRODUCTS
--3RD IMPORT TO CUSTOMERS
--4TH IMPORT TO SALES
